---

- name: install packages
  become: true
  apt:
    state: present
    name:
      - calibre
      - gnucash
      - keepassxc
      - newsboat
      - syncthing

- name: setup syncthing startup
  become: true
  ansible.builtin.systemd:
    # Start on boot
    enabled: true
    state: started
    name: syncthing@pawka.service

- name: install social apps for home use
  include: social.yml

- name: include dropbox.yml task
  include: dropbox.yml

- name: include sway.yml taks
  include: sway.yml
  tags: sway
