---

- name: install packages
  become: true
  apt:
    state: present
    name:
      - gnucash
      - keepassxc

- name: install social apps for home use
  include: social.yml

- name: include dropbox.yml task
  include: dropbox.yml
