---

- name: Check if Discord is installed
  command: dpkg-query -W discord
  register: check_discord
  failed_when: false
  changed_when: false

- name: install Discord
  become: true
  apt:
    deb: "https://discord.com/api/download?platform=linux&format=deb"
  when: check_discord.rc == 1
