---

- name: install sway
  become: true
  apt:
    state: present
    name:
      - gammastep
      - grim                # for screenshots
      - imv                 # image viewer
      - light
      - mako-notifier
      - rofi
      - slurp               # select region of wayland
      - sway
      - swaylock            # lockscreen
      - wl-clipboard        # clipboard tooling
      - wlogout

- name: download barista status bar
  get_url:
    url: https://git.io/fA7iT
    dest: "{{ ansible_env.HOME }}/bin/barista"
    mode: 0755

# User must belong to `video` group so screen brightness could be controlled via
# `light` binary. This requires user re-login to the system or reboot.
- name: Adding user {{ ansible_env.USER }} to video group
  become: true
  user: name={{ ansible_env.USER  }} groups=video append=yes
