---

- name: install sway
  become: true
  apt:
    state: present
    name:
      - light
      - mako-notifier
      - sway
      - wlogout

- name: download barista status bar
  get_url:
    url: https://git.io/fA7iT
    dest: "{{ ansible_env.HOME }}/bin/barista"
    mode: 0755
