---

- name: install sway
  become: true
  apt:
    state: present
    name:
      - fonts-font-awesome  # Fonts for waybar
      - fonts-fork-awesome  # Fonts for waybar
      - gammastep
      - grim                # for screenshots
      - imv                 # image viewer
      - light
      - mako-notifier
      - qalc                # Required for rofi-calc.
      - rofi
      - rofi-dev            # Required for rofi-calc.
      - slurp               # select region of wayland
      - sway
      - swayidle            # idle management
      - swaylock            # lockscreen
      - waybar              # statusbar
      - wl-clipboard        # clipboard tooling
      - wlogout

- name: check if barista binary exists
  command: which barista
  register: barista_installed
  failed_when: false
  changed_when: false

# User must belong to `video` group so screen brightness could be controlled via
# `light` binary. This requires user re-login to the system or reboot.
- name: Adding user {{ ansible_env.USER }} to video group
  become: true
  user: name={{ ansible_env.USER  }} groups=video append=yes

# Rofi calculator.
# Docs: https://github.com/svenstaro/rofi-calc
- name: clone rofi-calc
  git:
    repo: https://github.com/svenstaro/rofi-calc.git
    dest: "{{ansible_env.HOME}}/soft/rofi-calc"
    force: false
