---
- name: include st.yml task
  include: st.yml

- name: install packages
  become: true
  apt: name="{{item}}" state=present
  with_items:
    - fonts-powerline  # Used by VIM.

- name: check if fzf binary exists
  command: which fzf
  register: fzf_installed
  failed_when: false
  changed_when: false

- name: clone fzf repository
  git: repo=https://github.com/junegunn/fzf.git dest="{{ansible_env.HOME}}/soft/fzf" force=true depth=1
  when: fzf_installed.rc == 1

- name: install fzf
  command: "{{ansible_env.HOME}}/soft/fzf/install --all --no-fish --64"
  when: fzf_installed.rc == 1

- name: check if ripgrep is installed
  command: dpkg-query -W ripgrep
  register: ripgrep_installed
  failed_when: false
  changed_when: false

- name: install ripgrep deb package
  become: true
  apt:
    deb: "https://github.com/BurntSushi/ripgrep/releases/download/12.0.0/ripgrep_12.0.0_amd64.deb"
  when: ripgrep_installed.rc == 1
