# Gnome tools

- name: Add yktooo/ppa repository for indicator-sound-switcher
  ansible.builtin.apt_repository:
    repo: 'ppa:yktooo/ppa'

- name: install packages for gnome
  become: true
  apt:
    state: present
    name:
      - indicator-sound-switcher
