---
- name: create directories
  file: path="{{ansible_env.HOME}}/{{item}}" mode=0755 state=directory
  with_items:
    - bin
    - Documents
    - projects
    - soft
    - tmp

- name: run fresh install setup
  include: setup.yml

- name: include social tools
  include: social.yml

- name: include dropbox.yml task
  include: dropbox.yml
