---

- name: install packages
  become: true
  apt: name="{{item}}" state=present
  with_items:
    - autojump
    - cmake
    - curl
    - git
    - gnucash
    - jq
    - net-tools
    - p7zip-full
    - pwgen
    - silversearcher-ag
    - taskwarrior
    - tig
    - tmux
    - tree
    - urlview
    - vim
    - xclip
    - zsh

- name: install packages for development
  become: true
  apt: name="{{item}}" state=present
  with_items:
    - colordiff
    - docker
    - docker-compose
    - exuberant-ctags
    - golang
    - ipython
    - mysql-client
    - npm
    - php
    - php-curl
    - php-gd
    - php-mbstring
    - php-mysql
    - php-xdebug
    - php-xml
    - python-dev
    - python-flake8
    - python-pip
    - python-pytest
    - virtualenv

- name: install packages for multimedia
  become: true
  apt: name="{{item}}" state=present
  with_items:
    - gimp


- name: create directories
  file: path="{{ansible_env.HOME}}/{{item}}" mode=0755 state=directory
  with_items:
    - bin
    - Documents
    - projects
    - soft
    - tmp

- name: include dropbox.yml task
  include: dropbox.yml

- name: clone dotfiles
  git: repo=https://github.com/Pawka/dotfiles.git dest="{{ansible_env.HOME}}/projects/dotfiles" force=true

- name: install dotfiles
  make: chdir={{ansible_env.HOME}}/projects/dotfiles target=install

- name: Configure php.ini
  become: true
  tags:
    - php
  ini_file:
    path: /etc/php/7.2/mods-available/xdebug.ini
    section: xdebug
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    # Vdebug setup
    - { option: "xdebug.remote_enable", value: "on" }
    - { option: "xdebug.remote_handler", value: "dbgp" }
    - { option: "xdebug.remote_host", value: "localhost" }
    - { option: "xdebug.remote_port", value: "9000" }

- name: Clone phpctags
  tags:
    - php
  git:
    repo: https://github.com/vim-php/phpctags
    dest: "{{ ansible_env.HOME }}/soft/phpctags"
    force: true

- name: Install global npm packages
  become: true
  tags:
    - javascript
  npm:
    name: "{{item}}"
    global: yes
  with_items:
    - jshint
