---

- name: install packages
  become: true
  apt: name="{{item}}" state=present
  with_items:
    - autojump
    - cmake
    - curl
    - git
    - jq
    - p7zip-full
    - silversearcher-ag
    - taskwarrior
    - tig
    - tmux
    - tree
    - urlview
    - vim
    - xclip
    - zsh

- name: install packages for development
  become: true
  apt: name="{{item}}" state=present
  with_items:
    - docker
    - docker-compose
    - golang
    - mysql-client
    - php
    - php-curl
    - php-gd
    - php-mbstring
    - php-mysql
    - python-dev
    - python-flake8
    - python-pip
    - python-pytest
    - virtualenv

- name: install packages for multimedia
  become: true
  apt: name="{{item}}" state=present
  with_items:
    - gimp


- name: create directories
  file: path="{{ansible_env.HOME}}/{{item}}" mode=0755 state=directory
  with_items:
    - bin
    - Documents
    - projects
    - tmp

- name: clone dotfiles
  git: repo=https://github.com/Pawka/dotfiles.git dest="{{ansible_env.HOME}}/projects/dotfiles" force=true

- name: install dotfiles
  make: chdir={{ansible_env.HOME}}/projects/dotfiles target=install
