---

- name: install packages
  become: true
  apt:
    state: present
    name:
      - autojump
      - cmake
      - curl
      - direnv
      - git
      - gnucash
      - jq
      - keepassxc
      - net-tools
      - openvpn
      - p7zip-full
      - pwgen
      - taskwarrior
      - tig
      - tmux
      - tree
      - urlview
      - vim
      - whois
      - xclip
      - zsh

- name: install packages for development
  become: true
  apt:
    state: present
    name:
      - awscli
      - colordiff
      - dh-make
      - docker
      - docker-compose
      - exuberant-ctags
      - graphviz
      - mercurial
      - mysql-client
      - shellcheck

- name: install packages for multimedia
  become: true
  apt:
    state: present
    name:
      - gimp
      - vlc


- name: create directories
  file: path="{{ansible_env.HOME}}/{{item}}" mode=0755 state=directory
  with_items:
    - bin
    - Documents
    - projects
    - soft
    - tmp

- name: include social tools
  include: social.yml

- name: include dropbox.yml task
  include: dropbox.yml

- name: include php.yml task
  include: php.yml
  tags: php

- name: include python.yml task
  include: python.yml
  tags: python

- name: include golang.yml task
  include: golang.yml
  tags: golang

- name: clone dotfiles
  git: repo=https://github.com/Pawka/dotfiles.git dest="{{ansible_env.HOME}}/projects/dotfiles" force=true

- name: install dotfiles
  make: chdir={{ansible_env.HOME}}/projects/dotfiles target=install

- name: include cli.yml task
  include: cli.yml

- name: include i3wm.yml task
  include: i3wm.yml
  tags: i3wm

- name: include js.yml task
  include: js.yml
  tags: js
