---

- name: install packages
  become: true
  apt: name="{{item}}" state=present
  with_items:
    - autojump
    - cmake
    - curl
    - git
    - gnucash
    - jq
    - net-tools
    - p7zip-full
    - pwgen
    - silversearcher-ag
    - taskwarrior
    - tig
    - tmux
    - tree
    - urlview
    - vim
    - xclip
    - zsh

- name: install packages for development
  become: true
  apt: name="{{item}}" state=present
  with_items:
    - colordiff
    - docker
    - docker-compose
    - exuberant-ctags
    - golang
    - ipython
    - mysql-client
    - npm
    - python-dev
    - python-flake8
    - python-pip
    - python-pytest
    - virtualenv

- name: install packages for multimedia
  become: true
  apt: name="{{item}}" state=present
  with_items:
    - gimp


- name: create directories
  file: path="{{ansible_env.HOME}}/{{item}}" mode=0755 state=directory
  with_items:
    - bin
    - Documents
    - projects
    - soft
    - tmp

- name: include st.yml task
  include: st.yml

- name: include dropbox.yml task
  include: dropbox.yml

- name: include php.yml task
  include: php.yml

- name: clone dotfiles
  git: repo=https://github.com/Pawka/dotfiles.git dest="{{ansible_env.HOME}}/projects/dotfiles" force=true

- name: install dotfiles
  make: chdir={{ansible_env.HOME}}/projects/dotfiles target=install

- name: Install global npm packages
  become: true
  tags:
    - javascript
  npm:
    name: "{{item}}"
    global: yes
  with_items:
    - jshint
