---
- name: install packages for common use
  become: true
  apt:
    state: present
    name:
      - ntp # For keeping time in sync.

- name: create directories
  file: path="{{ansible_env.HOME}}/{{item}}" mode=0755 state=directory
  with_items:
    - bin
    - Documents
    - projects
    - soft
    - tmp

- name: run fresh install setup
  include_tasks: setup.yml

- name: include social tools
  include_tasks: social.yml

- name: include security tools
  include_tasks: security.yml
  tags: security

- name: setup gnome
  include_tasks: gnome.yml

- name: install obsidian
  become: true
  snap:
    name: obsidian
    classic: true
