---
- name: install packages for common use
  become: true
  apt:
    state: present
    name:
      - ntp # For keeping time in sync.

- name: create directories
  file: path="{{ansible_env.HOME}}/{{item}}" mode=0755 state=directory
  with_items:
    - bin
    - Documents
    - projects
    - soft
    - tmp

- name: run fresh install setup
  include_tasks: setup.yml

- name: include social tools
  include_tasks: social.yml

- name: setup gnome
  include_tasks: gnome.yml

- name: check if veracrypt is installed
  command: dpkg-query -W veracrypt
  register: veracrypt_installed
  failed_when: false
  changed_when: false

- name: install veracrypt deb package
  become: true
  apt:
    deb: "https://launchpad.net/veracrypt/trunk/{{ veracrypt_version }}/+download/veracrypt-{{ veracrypt_version }}-Ubuntu-21.04-amd64.deb"
  when: veracrypt_installed.rc == 1

- name: install obsidian
  become: true
  snap:
    name: obsidian
    classic: true
