---

- name: Check if discodn is installed
  command: dpkg-query -W discord
  register: check_discord
  failed_when: false
  changed_when: false

- name: install discord
  become: true
  apt:
    deb: "https://discord.com/api/download?platform=linux&format=deb"
  when: check_discord.rc == 1

- name: Check if slack is installed
  command: dpkg-query -W slack-desktop
  register: check_slack
  failed_when: false
  changed_when: false

- name: install slack
  become: true
  apt:
    deb: "https://downloads.slack-edge.com/releases/linux/4.21.1/prod/x64/slack-desktop-4.21.1-amd64.deb"
  when: check_slack.rc == 1
