---

- name: install packages for multimedia
  become: true
  apt:
    state: present
    name:
      - exiftool
      - gimp
      - imagemagick
      - pulseaudio
      - qrencode
      - vlc

- name: install snap packages for multimedia
  become: true
  snap:
    name:
      - spotify

- name: install packages for hobbies
  include_tasks: hobbies.yml
