---

- name: install packages for multimedia
  become: true
  apt:
    state: present
    name:
      - exiftool
      - gimp
      - vlc

- name: install snap packages for multimedia
  become: true
  snap:
    name:
      - spotify
