---

- name: install packages for npm
  become: true
  apt:
    state: present
    name:
      - npm

- name: Install global npm packages
  become: true
  npm:
    name: "{{item}}"
    global: yes
  with_items:
    - jshint
