---

- name: install packages for development
  become: true
  apt:
    state: present
    name:
      - colordiff
      - dh-make
      - exuberant-ctags
      - graphviz
      - mysql-client
      - shellcheck

- name: install snap packages for development
  become: true
  snap:
    classic: true
    name:
      - aws-cli

- name: include rust.yml task
  include_tasks: rust.yml
  tags: rust

- name: include php.yml task
  include_tasks: php.yml
  tags: php

- name: include python.yml task
  include_tasks: python.yml
  tags: python

- name: include golang.yml task
  include_tasks: golang.yml
  tags: golang

- name: include js.yml task
  include_tasks: js.yml
  tags: js

- name: include docker.yml task
  include_tasks: docker.yml
  tags: docker
