---

- name: install packages for development
  become: true
  apt:
    state: present
    name:
      - awscli
      - colordiff
      - dh-make
      - exuberant-ctags
      - graphviz
      - mysql-client
      - shellcheck

- name: include rust.yml task
  include: rust.yml
  tags: rust

- name: include php.yml task
  include: php.yml
  tags: php

- name: include python.yml task
  include: python.yml
  tags: python

- name: include golang.yml task
  include: golang.yml
  tags: golang

- name: include js.yml task
  include: js.yml
  tags: js

- name: include docker.yml task
  include: docker.yml
  tags: docker
