- name: check if fzf binary exists
  command: which fzf
  register: fzf_installed
  failed_when: false
  changed_when: false

- name: clone fzf repository
  git: repo=https://github.com/junegunn/fzf.git dest="{{ansible_env.HOME}}/soft/fzf" force=true depth=1
  when: fzf_installed.rc == 1

- name: install fzf
  command: "{{ansible_env.HOME}}/soft/fzf/install --all --no-fish"
  when: fzf_installed.rc == 1

- name: check if ripgrep is installed
  command: dpkg-query -W ripgrep
  register: ripgrep_installed
  failed_when: false
  changed_when: false

- name: install ripgrep deb package
  become: true
  apt:
    deb: "https://github.com/BurntSushi/ripgrep/releases/download/{{ ripgrep_version }}/ripgrep_{{ ripgrep_version }}_amd64.deb"
  when: ripgrep_installed.rc == 1

- name: include st.yml task
  include: st.yml
