---

- name: install packages
  become: true
  apt:
    state: present
    name:
      - autojump
      - cmake
      - curl
      - direnv
      - git
      - jq
      - net-tools
      - p7zip-full
      - pwgen
      - ranger
      - taskwarrior
      - tig
      - tmux
      - tree
      - urlview
      - vim
      - whois
      - xclip
      - zsh

- name: clone dotfiles
  git:
    repo: https://github.com/Pawka/dotfiles.git
    dest: "{{ansible_env.HOME}}/projects/dotfiles"
    force: false

- name: set remote to SSH for dotfiles
  git_config:
    repo: "{{ansible_env.HOME}}/projects/dotfiles"
    scope: local
    name: remote.origin.url
    value: git@github.com:Pawka/dotfiles.git

- name: install dotfiles
  make: chdir={{ansible_env.HOME}}/projects/dotfiles target=install

- name: check if fzf binary exists
  command: which fzf
  register: fzf_installed
  failed_when: false
  changed_when: false

- name: clone fzf repository
  git: repo=https://github.com/junegunn/fzf.git dest="{{ansible_env.HOME}}/soft/fzf" force=true depth=1
  when: fzf_installed.rc == 1

- name: install fzf
  command: "{{ansible_env.HOME}}/soft/fzf/install --all --no-fish"
  when: fzf_installed.rc == 1

- name: check if ripgrep is installed
  command: dpkg-query -W ripgrep
  register: ripgrep_installed
  failed_when: false
  changed_when: false

- name: install ripgrep deb package
  become: true
  apt:
    deb: "https://github.com/BurntSushi/ripgrep/releases/download/{{ ripgrep_version }}/ripgrep_{{ ripgrep_version }}_amd64.deb"
  when: ripgrep_installed.rc == 1

- name: install neovim deb package
  become: true
  apt:
    deb: "https://github.com/neovim/neovim/releases/download/v{{ neovim_version }}/nvim-linux64.deb"

- name: include st.yml task
  include: st.yml
