---

- name: check if st binary exists
  command: which st
  register: st_installed
  failed_when: false
  changed_when: false

- name: clone st repository
  git: repo=https://github.com/Pawka/st.git dest="{{ansible_env.HOME}}/soft/st" force=true
  when: st_installed.rc == 1

- name: install dependencies for st
  become: true
  apt:
    state: present
    name:
      - fonts-symbola # st may crash when color emoji font is used.
      - libx11-dev
      - libxext-dev
      - libxft-dev

- name: compile st
  become: true
  make:
    chdir: "{{ansible_env.HOME}}/soft/st"
    target: clean
  when: st_installed.rc == 1

- name: compile st
  become: true
  make:
    chdir: "{{ansible_env.HOME}}/soft/st"
    target: install
  when: st_installed.rc == 1

# The Desktop file makes application available on launchers.
- name: create st Desktop file
  become: true
  copy:
    dest: "/usr/share/applications/st.desktop"
    content: |
      [Desktop Entry]
      Name=st Terminal
      Comment=st is simply the best terminal
      Exec=st
      Icon=utilities-terminal
      Terminal=false
      Type=Application
      Categories=System;TerminalEmulator;
